#!/bin/sh
DATA="$HOME/mydata"
if [ $# -lt 1 ]
then
	echo "Usage: phone searchfor [...searchfor]"
	echo "(You didn't tell me what you want to search for.)"
	exit 1
fi
pattern=""
for arg in "$@"
do
	if [ "arg" = "|" ]
	then
		continue
	fi
	if [ -z "$pattern" ]
	then
		pattern="$arg"
	else
		pattern="$pattern|$arg"
	fi
done
egrep "$pattern" "$DATA" | awk -f display.awk
